# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      ? linux_64_DEFAULT_CUDAARCHS75-real;80-real;86-real;89-real;90-real;100-real;103-real;120-real;121DEFAULT_TORCH_CUDA_ARCH_LIST7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0;12.1+PTXarm_variant_targetNonec_hc9020746
      : CONFIG: linux_64_DEFAULT_CUDAARCHS75-real;80-real;86-real;89-real;90-real;100-real;103-real;120-real;121DEFAULT_TORCH_CUDA_ARCH_LIST7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0;12.1+PTXarm_variant_targetNonec_hc9020746
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_64_DEFAULT_CUDAARCHS75-real;80-real;86-real;89-real;90-real;100-real;103-real;120-real;121DEFAULT_TORCH_CUDA_ARCH_LIST7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0;12.1+PTXarm_variant_targetsbsac_h964ac52a
      : CONFIG: linux_64_DEFAULT_CUDAARCHS75-real;80-real;86-real;89-real;90-real;100-real;103-real;120-real;121DEFAULT_TORCH_CUDA_ARCH_LIST7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0;12.1+PTXarm_variant_targetsbsac_h964ac52a
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      linux_64_DEFAULT_CUDAARCHS87DEFAULT_TORCH_CUDA_ARCH_LIST8.7+PTXarm_variant_targettegracross_target_platformlinux-aarch64:
        CONFIG: linux_64_DEFAULT_CUDAARCHS87DEFAULT_TORCH_CUDA_ARCH_LIST8.7+PTXarm_variant_targettegracross_target_platformlinux-aarch64
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_aarch64_DEFAULT_CUDAARCHS75-real;80-real;86-real;89-real;90-real;100-real;103-real;120-real;121DEFAULT_TORCH_CUDA_ARCH_LIST7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0;12.1+PTXarm_variant_target_h64189495
      : CONFIG: linux_aarch64_DEFAULT_CUDAARCHS75-real;80-real;86-real;89-real;90-real;100-real;103-real;120-real;121DEFAULT_TORCH_CUDA_ARCH_LIST7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0;12.1+PTXarm_variant_target_h64189495
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
      ? linux_aarch64_DEFAULT_CUDAARCHS87DEFAULT_TORCH_CUDA_ARCH_LIST8.7+PTXarm_variant_targettegracross_target_platformlinux-aarch64
      : CONFIG: linux_aarch64_DEFAULT_CUDAARCHS87DEFAULT_TORCH_CUDA_ARCH_LIST8.7+PTXarm_variant_targettegracross_target_platformlinux-aarch64
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
  timeoutInMinutes: 360
  variables: {}

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
